site_name: NeMo Data Designer
repo_url: https://github.com/NVIDIA-NeMo/DataDesigner

nav:
  - Getting Started:
      - Welcome to Data Designer: index.md
      - Installation: installation.md
      - Quick Start: quick-start.md
      - Contributing: CONTRIBUTING.md
  - Concepts:
      - Columns: concepts/columns.md
      - Plugins: concepts/plugins.md
  - Tutorials:
      - The Basics: notebooks/1-the-basics.ipynb
      - Structured Outputs and Jinja Expressions: notebooks/2-structured-outputs-and-jinja-expressions.ipynb
      - Seeding with an External Dataset: notebooks/3-seeding-with-a-dataset.ipynb
  - Models:
      - Default Model Settings: models/default-model-settings.md
      - Configure with the CLI: models/configure-model-settings-with-the-cli.md
      - Model Providers: models/model-providers.md
      - Model Configs: models/model-configs.md
  - Code Reference:
      - column_configs: code_reference/column_configs.md
      - config_builder: code_reference/config_builder.md
      - data_designer_config: code_reference/data_designer_config.md

theme:
  name: material
  font:
    text: Roboto
    code: Fira Code
  icon:
      logo: fontawesome/solid/palette
      repo: fontawesome/brands/github-alt
  favicon: assets/palette-favicon.png
  palette:
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: black
        toggle:
            icon: material/lightbulb-outline
            name: Switch to light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: black
        toggle:
            icon: material/lightbulb
            name: Switch to dark mode
  features:
      - navigation.tabs
      - navigation.sections
      - navigation.expand
      - navigation.path
      - content.code.copy
      - content.code.select
      - content.code.annotate

extra:
  version:
    provider: mike

watch:
  - src/data_designer
  - docs/

plugins:
  - search
  - mike:
      alias_type: symlink
      canonical_version: latest
  - mkdocs-jupyter:
        execute: false
        include_requirejs: true
        ignore_h1_titles: True
  - mkdocstrings:
      handlers:
          python:
              options:
                  show_symbol_type_heading: true
                  show_symbol_type_toc: true
                  show_root_toc_entry: true
                  show_object_full_path: false
                  filters: ["!^_"]
                  docstring_options:
                      ignore_init_summary: false
                  merge_init_into_class: true
                  docstring_section_style: table
                  summary: true

extra_css:
  - css/style.css
  - css/mkdocstrings.css

extra_javascript:
  - js/toc-toggle.js

markdown_extensions:
  - pymdownx.highlight:
        pygments_lang_class: true
        use_pygments: true
  - tables
  - pymdownx.superfences
  - pymdownx.tabbed:
        alternate_style: true
  - attr_list
  - md_in_html
  - admonition
